StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{62A0219BF1BAB878}" {
   Id "SPC_EditableEntity_JLTV_CROWS_Black_Name"
   Target_en_us "JLTV CROWS Black"
   Modified 1654663156
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
  CustomStringTableItem "{62A0219BFEEE91F1}" {
   Id "SPC_EditableEntity_JLTV_CROWS_Name"
   Target_en_us "JLTV CROWS"
   Modified 1654663162
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
  CustomStringTableItem "{6212E2E5D773AFB4}" {
   Id "SPC_EditableEntity_JLTV_CROWS_Olive_Name"
   Target_en_us "JLTV CROWS Olive"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1645405531
   Author "tonimontana"
   LastChanged "tonimontana"
  }
  CustomStringTableItem "{5C8898DF0DE78297}" {
   Id "SPC_EditableEntity_JLTV_CROWSII_Black_Name"
   Target_en_us "JLTV CROWSII Black"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1552456488
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
   Labels {
    300
   }
   SourceFile "{41F4B0594B760AD2}Prefabs/Vehicles/Wheeled/JLTV/JLTV_CROWSII_Black.et"
  }
  CustomStringTableItem "{5C8898DF0DE55E65}" {
   Id "SPC_EditableEntity_JLTV_CROWSII_Name"
   Target_en_us "JLTV CROWSII"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1552456483
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
   Labels {
    300
   }
   SourceFile "{49B5C8D1F28E7B7F}Prefabs/Vehicles/Wheeled/JLTV/JLTV_CROWSII.et"
  }
  CustomStringTableItem "{5C8898DF0DE055EC}" {
   Id "SPC_EditableEntity_JLTV_CROWSII_Olive_Name"
   Target_en_us "JLTV CROWSII Olive"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1552456481
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
   Labels {
    300
   }
   SourceFile "{225A9305129485F1}Prefabs/Vehicles/Wheeled/JLTV/JLTV_CROWSII_Olive.et"
  }
  CustomStringTableItem "{5C8898DF0DFC8F35}" {
   Id "SPC_EditableEntity_JLTV_OGPK_Black_Name"
   Target_en_us "JLTV OGPK Black"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1552456477
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
   Labels {
    300
   }
   SourceFile "{5544A492985CF8C3}Prefabs/Vehicles/Wheeled/JLTV/JLTV_OGPK_Black.et"
  }
  CustomStringTableItem "{5C8898DF0DFD31FF}" {
   Id "SPC_EditableEntity_JLTV_OGPK_Name"
   Target_en_us "JLTV OGPK"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1552456471
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
   Labels {
    300
   }
   SourceFile "{E49B4C9AEA70BE3F}Prefabs/Vehicles/Wheeled/JLTV/JLTV_OGPK.et"
  }
  CustomStringTableItem "{5C8898DF0DE1124F}" {
   Id "SPC_EditableEntity_JLTV_OGPK_Olive_Name"
   Target_en_us "JLTV OGPK Olive"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1552456468
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
   Labels {
    300
   }
   SourceFile "{36EA87CEC1BE77E0}Prefabs/Vehicles/Wheeled/JLTV/JLTV_OGPK_Olive.et"
  }
  CustomStringTableItem "{5C8898DF0DFA82DA}" {
   Id "SPC_EditableEntity_JLTV_Unarmed_Black_Name"
   Target_en_us "JLTV Unarmed Black"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1552456463
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
   Labels {
    300
   }
   SourceFile "{3A66B6586464A16C}Prefabs/Vehicles/Wheeled/JLTV/JLTV_Unarmed_Black.et"
  }
  CustomStringTableItem "{5C8898DF0DFFF41F}" {
   Id "SPC_EditableEntity_JLTV_Unarmed_Name"
   Target_en_us "JLTV Unarmed"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1552456458
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
   Labels {
    300
   }
   SourceFile "{E62EEF185EC31C54}Prefabs/Vehicles/Wheeled/JLTV/JLTV_Unarmed.et"
  }
  CustomStringTableItem "{5C8898DF0DF9F36D}" {
   Id "SPC_EditableEntity_JLTV_Unarmed_Olive_Name"
   Target_en_us "JLTV Unarmed Olive"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1552456229
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
   Labels {
    300
   }
   SourceFile "{59C895043D862E4F}Prefabs/Vehicles/Wheeled/JLTV/JLTV_Unarmed_Olive.et"
  }
 }
}